version: "3"

networks:
  shastho-sheba:
    external: true

services:
  nginx:
    build:
      context: ./.docker
      dockerfile: ./nginx-dockerfile
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./.docker/vhost.conf:/etc/nginx/conf.d/default.conf
    #      - ./log:/var/log/nginx
    ports:
      - 8000:8080
    links:
      - php-fpm
    networks:
      - shastho-sheba

  php-fpm:
    build:
      context: ./.docker
      dockerfile: php-dockerfile
    working_dir: /var/www
    volumes:
      - ./:/var/www
    #      - ./.docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini
    #      - ./.docker/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    ports:
      - 9000:9000
    links:
      - mysql
    networks:
      - shastho-sheba
    environment:
      DB_HOST: mysql
      DB_DATABASE: shastho-sheba
      DB_USERNAME: root
      DB_PASSWORD: secret

  mysql:
    image: mysql:5.6
    restart: always
    volumes:
      - dbdata:/var/lib/mysql
      - ./data:/docker-entrypoint-initdb.d
    ports:
      - 3308:3306
    networks:
      - shastho-sheba
    command:
      [
        "mysqld",
        "--character-set-server=utf8mb4",
        "--collation-server=utf8mb4_unicode_ci",
      ]
    environment:
      MYSQL_DATABASE: shastho-sheba
      MYSQL_USER: shastho
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret

volumes:
  dbdata:
